CREATE DATABASE PLUS;
USE PLUS;

CREATE TABLE usuario(
id_usuario INT NOT NULL AUTO_INCREMENT,
password VARCHAR(32) NOT NULL,
email VARCHAR(255) NOT NULL,
nombrePila VARCHAR(64) NOT NULL,
apellidoPate VARCHAR(64) NOT NULL,
apellidoMate VARCHAR(64) DEFAULT '',
PRIMARY KEY(id_usuario)
)ENGINE=INNODB;

CREATE TABLE sesiones(


)ENGINE=INNODB;

CREATE TABLE cursos(



)ENGINE=INNODB;

CREATE TABLE lista_Sesiones(

)ENGINE=INNODB;

CREATE TABLE lista_Inscritos(


)ENGINE=INNODB;
